version: "3.5"

services:

  redis:
    image: redis
    container_name: "redis_db"
    # --------------------------------------------------------
    # NOTE: must not enable password auth because broadcaster does
    # not yet support that. See MR #79
    # command: redis-server --requirepass __password__
    # --------------------------------------------------------
    command: redis-server
    ports:
      - "6380:6379"
    networks:
      - colabdict

  backend:
    build:
      context: ./backend
    container_name: "colabdict-api"
    command: ["bash", "-c", "./run.sh"]
    volumes:
      - ./backend:/code
    ports:
      - 8080:8080
    networks:
      - colabdict
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    container_name: "colabdict-ui"
    command: ["npm", "start"]
    volumes:
      - ./frontend/src:/code/src
    ports:
      - 3000:3000
    networks:
      - colabdict
    env_file:
      - .env

networks:
  colabdict:
    name: colabdict-network
